### ISSUE TITLE
Error using actual AndroidStudio 3.4 

### ISSUE THREAD

**Issue by fridemar** [DonBrody/Android-CustomKeyboard#1]
Dear DonBrody,

using the newest AndroidStudio 3.4 
"""
Android Studio 3.4
Build #AI-183.5429.30.34.5452501, built on April 10, 2019
JRE: 1.8.0_152-release-1343-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
"""
the following error + warning occurred:

"""
ERROR: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
root project 'Android-CustomKeyboard' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.30
Affected Modules: app

WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app
"""

My app/build.gradle that lead to the error looks like this (within the triple quotes):

"""
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.donbrody.customkeyboard"
        minSdkVersion 23
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
"""
Here it appeared that the dependency:
implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
was the culprit.

Any help how to correct this would be greatly appreciated.
Thank you
Fridemar
PS:
Thank you for contributing the custom keyboard. My use case was a small
customized "NUM" kb with digits,'+' and '-', and a ENTER  for inputting a string "xyz.." where x,y or z
can be digits or embedded sign-chars, e.g. like in "912-32+34".

Using the standard attribute for an editfield >android:inputType="numberSigned"< 
doesn't allow to type interspersed signs +,-. The system suppresses it.

I figured out the following solution for the gradle dependency files:

"""
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.30'
    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
"""

On module level I used:

"""
...

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

"""

**Comment by DonBrody** [comment]
Sorry to take so long getting back to you. It sounds like there is a dependency conflict with the Kotlin/Gradle versions. You should just be able to change the Kotlin version to the one you need.
